"""adicionar coluna 'auth2'

Revision ID: 186271c51f0a
Revises: d37b7c15f101
Create Date: 2025-01-17 15:16:43.552983

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '186271c51f0a'
down_revision = 'd37b7c15f101'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('auth2', sa.Boolean(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('auth2')

    # ### end Alembic commands ###
