"""adicionar coluna 'telefone' na tabela 'users'

Revision ID: d37b7c15f101
Revises: 0d65a81bd00c
Create Date: 2025-01-16 06:56:42.853086

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd37b7c15f101'
down_revision = '0d65a81bd00c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('telefone', sa.String(length=15), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_column('telefone')

    # ### end Alembic commands ###
